# Generated by Django 4.2.3 on 2024-04-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=32)),
            ],
        ),
    ]
