# Generated by Django 4.2.3 on 2024-04-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banhang", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
