name: auto_deployment

on:
  pull_request:
  push:
    branches:
      - dev
      - feature/lyh_auto_deployment

jobs:
  eslint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: schtasks /End /TN BanHang
      - run: if (Test-Path -Path D:\SoftWareEngineer\backend\fastapi){Remove-Item -Path D:\SoftWareEngineer\backend\fastapi -Force -Recurse}
      - run: Copy-Item -Path .\backend\fastapi -Destination D:\SoftWareEngineer\backend -Force -Recurse
      - run: schtasks /Run /TN BanHang
