name: backend_pytest

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

jobs:
  prepare_files:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: if (Test-Path -Path D:\SoftWareEngineer\backend_test\fastapi){Remove-Item -Path D:\SoftWareEngineer\backend_test\fastapi -Force -Recurse}
      - run: Copy-Item -Path .\backend\fastapi -Destination D:\SoftWareEngineer\backend_test -Force -Recurse
      - run: .\runBackend.bat
        working-directory: D:\SoftWareEngineer\backend_test
