name: backend_pytest

on:
  push:
    branches:
      - dev

jobs:
  auto_deployment:
    runs-on: backend_pytest
    steps:
      - uses: actions/checkout@v3
      - run: if (Test-Path -Path D:\SoftWareEngineer\backend_test\fastapi){Remove-Item -Path D:\SoftWareEngineer\backend_test\fastapi -Force -Recurse}
      - run: Copy-Item -Path .\backend\fastapi -Destination D:\SoftWareEngineer\backend_test -Force -Recurse
      - run: cd D:\SoftWareEngineer\backend_test\fastapi\tests
      - run: pytest
